<a href="https://colab.research.google.com/github/eshghinezhad/NLP/blob/master/Text%20Representation/Text_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction
 A key difficulty in the complex field of NLP is to turn the unstructured jumble of natural language into structured, machine-readable data. This transition is essential because it powers a wide range of applications, including sophisticated sentiment analysis, intelligent conversational bots, improved search engine algorithms, and sophisticated recommendation systems. The methods used to accomplish this metamorphosis are numerous and intricate, each addressing a different facet of language and meeting a distinct set of computing requirements. This chapter examines the variety of semantic representation approaches that comprise the fundamental toolset of any NLP practitioner, emphasizing their importance, uses, and the nuanced interaction between their benefits and drawbacks.

 By the end of this chapter, readers will have gained a comprehensive understanding of semantic representation techniques for text data. They will learn how to move beyond simple bag-of-words models and leverage more advanced methods like TF-IDF, word embeddings, and as BERT to capture the rich meaning and context of words and documents. Through hands-on examples and practical recipes, readers will acquire the skills to implement these techniques using Python libraries, enabling them to apply semantic representations to real-world NLP problems. They will understand how to represent text using feature vectors, weight words by importance, capture context with N-grams, and embed words in vector space. Furthermore, readers will explore sentence embeddings, learn how to utilize pre-trained language models like BERT, and discover techniques for disambiguating word meanings and extracting semantic relationships. They will also gain insights into clustering words by meaning and comparing text similarity using cosine similarity. By mastering these semantic representation techniques, readers will be equipped with the knowledge and tools necessary to tackle a wide range of NLP tasks, such as text classification, sentiment analysis, and information retrieval, with improved accuracy and performance.

## Learning objectives
* Semantic representation techniques
* Bag-of-words model
* TF-IDF
* N-gram modeling
* Word embeddings
* Sentence embeddings
* BERT
* Semantic role labeling
* One-hot encoding
* Semantic clustering
* Cosine similarity
* Relationship extraction


 ## Semantic representation techniques
 The bag-of-words (BoW) model is the starting point of the journey; it is a simple yet powerful technique for text representation. This paradigm converts text into a set of tokens while keeping frequency constant and ignoring order, giving algorithms a basic degree of comprehension to work with. BoW is especially helpful in situations that need a simple quantitative examination of text, such document classification and initial topic identification. However, the main drawback of BoW is its simplicity: contextual information is lost, which is frequently essential for more complex language comprehension.

TF-IDF Calculation is a more sophisticated version of the BoW model that weighs terms according to their relevance, derived from their frequency within a text compared to their frequency throughout all papers. By reducing the influence of commonly used but less informative words, this technique improves the BoW and improves the feature set for tasks like search and information retrieval.

By capturing the local word order and offering a view into the contextual usage of words, N-gram modeling advances much farther. N-grams add a syntactic structural layer by taking into account tuples of consecutive words, which is very useful for statistical language modeling and speech recognition applications. However, higher computing costs and possible problems with data sparsity accompany the increasing granularity.

An even more sophisticated method is introduced by word embeddings and sentence embeddings, which map words and sentences into a continuous vector space where semantic links correspond to spatial proximity. These methods are essential for tasks like advanced sentiment analysis and machine translation, which call for a deep semantic knowledge of text. By considering the semantic similarity between words or sentences, they enable models to understand minute details.

A major development in NLP is the advent of pre-trained language models, such as BERT. These models provide contextually enriched embeddings and achieve breakthrough performance across a wide range of NLP tasks by utilizing large amounts of data and sophisticated neural network architectures. They provide unparalleled flexibility and power in NLP applications due to their fine-tuning capability, which allows them to adapt to unique tasks while maintaining a deep comprehension of linguistic nuances.

The specialized techniques, semantic role labeling and relationship extraction try to comprehend the underlying structure of sentences by determining the relationships between things inside a text. This is important for tasks like knowledge graph generation and information extraction. These techniques demonstrate the level of comprehension achievable with sophisticated NLP by looking into the syntax and semantics of language to extract structured relationships.

Various features of text representation and similarity measurement are addressed by techniques, such as cosine similarity, semantic clustering, and one-hot encoding. Although it ignores semantic complexity, one-hot encoding offers a simple technique for encoding items in a form that computers can comprehend. Similar entities are grouped together using semantic clustering, which improves information organization and retrieval. For applications such as plagiarism detectors and search engines’ ability to retrieve pertinent documents, cosine similarity provides a measure of how similar two documents are to one another.

With regard to the difficult issue of comprehending and interpreting natural language, each of these semantic representation strategies brings a unique set of tools to the table. NLP practitioners can address a wide range of applications by combining these diverse approaches, pushing the limits of what robots can comprehend and accomplish with human language. This introduction provides a thorough framework against which the complex tapestry of NLP is sewn, setting the way for a thorough examination of each technique.

##  Bag-of-words model
 Transforming textual input into a numerical format that can be easily comprehended and processed by computers is an important step in the field of NLP. The BoW model offers one of the most straightforward yet efficient ways to accomplish this transformation. The BoW model preserves multiplicity while ignoring grammar and word order, portraying text as a collection of individual words. Regarding tasks like document classification, this model is especially helpful because it can reveal more information about a word’s presence and frequency than its sequence of appearance.




###  BoW techniques
Here are some techniques of BoW:

* Text preprocessing: Depending on the application, the original text data is cleaned up by eliminating special characters, punctuation, and occasionally common terms (stop words).

* Tokenization: This is an important stage that defines how the words are identified; the cleaned text is divided into distinct terms or words.

* Vocabulary creation: Using the tokens, a vocabulary of distinct words is formed. Each distinct word is then given a location in the resultant vector, which becomes the feature set.

* Vectorization: Every text document or sentence is vectorized, with each dimension denoting the vocabulary and each value denoting the frequency of a word in the document.

* Normalization (optional): The raw frequency numbers may occasionally be normalized to take document length into consideration or to avoid features with higher counts from overshadowing features with lower counts.

Despite being straightforward, this approach serves as the basis for more intricate text representation strategies and is crucial to comprehending machine learning algorithms when applied to text.


###  Recipe 1: BoW  --> Sequence of word not matter
We will follow a step-by-step process using the scikit-learn package, which offers robust capabilities for feature extraction from text through its CountVectorizer class, to show how the BoW model may be implemented using Python. The following steps will help you understand how to implement BoW in Python:


1.  Install required libraries: Ensure that scikit-learn is installed in your Python environment, as it provides the CountVectorizer module and other NLP tools, as shown in the following command:

In [17]:
!pip install scikit-learn

 Import necessary modules: Import the CountVectorizer class from scikit-learn by running the following command:

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

3.  Define sample text: Create a simple array of documents to work with, as shown in the following code:

In [19]:
# we have 3 article so, 3 vectore we will have --- also not case sensitive
documents = [
	"Hello world",
	"Machine learning is fascinating",
	"Hello from the other side"
	]

 4. Create the vectorizer: Instantiate a CountVectorizer object, which will convert the text documents into vectors, as shown in the following command:

In [20]:
vectorizer = CountVectorizer()

5.  Fit and transform the documents: Fit the model on the documents and transform the text data into a BoW representation, as shown in the following command:

In [21]:
bow_model = vectorizer.fit_transform(documents)

 6. View the feature names and the dense representation of the matrix: Retrieve and print the feature names to see the vocabulary, and convert the sparse matrix to an array for visualization, as shown in the following command:

In [22]:
print("Vocabulary: ", vectorizer.get_feature_names_out())
print("Bag-of-Words Matrix:\n", bow_model.toarray())

Vocabulary:  ['fascinating' 'from' 'hello' 'is' 'learning' 'machine' 'other' 'side'
 'the' 'world']
Bag-of-Words Matrix:
 [[0 0 1 0 0 0 0 0 0 1]
 [1 0 0 1 1 1 0 0 0 0]
 [0 1 1 0 0 0 1 1 1 0]]


A document is represented by each row in the matrix, and a vocabulary term is represented by each column. The numbers show how frequently each word appears in each document. For instance, the word Hello is missing from the second paper but appears once in the first and third. In order to feed textual data into ML models for additional analysis and prediction tasks, this numerical representation is necessary.

##  TF-IDF
 Determining the significance of words within a corpus of documents in text analysis and NLP is crucial for many applications, including content summarization, information retrieval, and search engines. A statistical metric called TF-IDF is employed to assess a word’s significance to a document in a corpus or collection. This method works especially well in situations when word frequency varies greatly between papers.

###  TF-IDF techniques
The two parts of TF-IDF are the IDF and the TF. When combined, these elements provide a balance between a word’s frequency-based significance and its ubiquity throughout various sources. The following are the factors needed to calculate TF-IDF:
* TF: Indicates how often a word occurs in a given document. To avoid bias towards longer documents, it is commonly normalized by dividing by the total amount of words in the document.

* IDF: This quantifies a term’s significance over a collection of documents. IDF is based on the notion that a term’s importance rises inversely with its frequency across several publications.

* Combining TF and IDF: Multiplying TF and IDF yields the TF-IDF score. Important terms have a larger resultant value, which helps to offset the fact that certain words appear more frequently overall.

In addition to decreasing the weight of words that appear frequently in documents (like the, is, and at), TF-IDF also helps to boost the weight of phrases that appear essential but are less common.


 ### Recipe 2: TF-IDF
 To implement TF-IDF, we can use Python’s scikit-learn library, which provides built-in functions to calculate this statistic easily. Here is a step-by-step guide:

1. Install required libraries: First, ensure that you have scikit-learn installed, which includes the TfidfVectorizer class, as shown in the following command:

In [23]:
!pip install scikit-learn

2. Import necessary modules: Import the TfidfVectorizer from scikit-learn, as shown in the following command:

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

3. Define sample text: Prepare some example documents. Here we will use a small set, as shown in the following command:

In [25]:
documents = [
"Data science is about the extraction of knowledge from data.",
"Machine learning is a subset of data science.",
"Statistics is important for data analysis."]

4. Create the TF-IDF vectorizer: Instantiate the TfidfVectorizer object, which will be used to convert the text documents into a matrix of TF-IDF features, as shown in the following command:

In [26]:
tfidf_vectorizer = TfidfVectorizer()

5.  Fit and transform the documents: Fit the model and transform the documents, as shown in the following:

In [27]:
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

6.  View the feature names and the TF-IDF matrix: Get and print the feature names to see the vocabulary, and display the TF-IDF matrix, as shown in the following command:

In [28]:
print("Vocabulary: ", tfidf_vectorizer.get_feature_names_out())
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())

Vocabulary:  ['about' 'analysis' 'data' 'extraction' 'for' 'from' 'important' 'is'
 'knowledge' 'learning' 'machine' 'of' 'science' 'statistics' 'subset'
 'the']
TF-IDF Matrix:
 [[0.35576296 0.         0.42023867 0.35576296 0.         0.35576296
  0.         0.21011934 0.35576296 0.         0.         0.2705669
  0.2705669  0.         0.         0.35576296]
 [0.         0.         0.26806191 0.         0.         0.
  0.         0.26806191 0.         0.45386827 0.45386827 0.34517852
  0.34517852 0.         0.45386827 0.        ]
 [0.         0.46138073 0.27249889 0.         0.46138073 0.
  0.46138073 0.27249889 0.         0.         0.         0.
  0.         0.46138073 0.         0.        ]]


A document is represented by each row in the matrix, and a word from the total vocabulary is represented by each column. The values show the TF-IDF score, which highlights words that may be especially indicative of a document within the set by quantifying the relative importance of each word per document.

## N-gram modeling
 Understanding the context in which words arise greatly improves language interpretation and analysis in the field of NLP. A simple yet effective method for collecting this linguistic context is N-gram modeling. A continuous series of n elements (words or letters) from a specific text or speech sample is called an n-gram. By taking word sequences into account, this strategy goes beyond basic word frequency models and adds order and context to the study. For applications like text prediction, language modeling, and spelling correction, n-grams are essential.

 ### N-gram modeling techniques
 N-gram models are based on the supposition that a word’s likelihood is solely determined by the number of words that came before it. This presumption preserves a meaningful level of contextuality while managing to simplify the difficult process of language modeling. Typically, n-gram modeling implementation entails the following steps:

* Text preprocessing: The text is cleaned and ready by converting it to lowercase, eliminating stopwords occasionally, and removing punctuation.

* Tokenization: A list of tokens (words) is created by splitting the cleaned text.

* N-gram generation: The token list is used to create N-grams. To do this, tuples of n consecutive words must be formed across the text.

* N-gram frequency distribution: Following the generation of n-grams, the frequency at which they occur within the corpus is determined.

* Probability estimation: Frequently, methods such as maximum likelihood estimation are used to assign probabilities to sequences based on their frequencies.

* Smoothing (optional): The probability estimates for unseen n-grams might be adjusted by using smoothing techniques, as not all conceivable n-grams will show up in the training data.

Depending on the value of n, N-gram models can differ greatly in terms of accuracy and complexity. More context is indicated by a greater n, but managing the continually increasing number of possible n-grams demands more data and processing capacity.

 ### Recipe 3: N-gram modeling
 This recipe will demonstrate how to implement a basic n-gram model using Python’s NLTK, which provides comprehensive support for building NLP models. Follow these steps:

1.  Install required libraries: Ensure that you have the NLTK library installed, which will be used to handle text processing and N-gram generation:

In [29]:
!pip install nltk

2.  Import necessary modules: Import the necessary components from NLTK:

In [30]:
import nltk
nltk.download('punkt_tab')
from nltk.util import ngrams
from nltk import FreqDist

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


3. Define sample text: Define some text to work with. This text will be converted into N-grams:

In [31]:
text = "The quick brown fox jumps over the lazy dog. The quick brown fox is very friendly."

4.  Tokenize and preprocess: Tokenize the text and convert all tokens to lowercase:

In [32]:
tokens = nltk.word_tokenize(text.lower())

5. Generate N-grams: Generate N-grams from tokens. Here, we choose trigrams (n=3) as an example:

In [63]:
trigrams = list(ngrams(tokens, 3))
print ("3-grams",trigrams)

3-grams [('gensim', 'is', 'a'), ('is', 'a', 'free'), ('a', 'free', 'python'), ('free', 'python', 'library'), ('python', 'library', 'designed'), ('library', 'designed', 'to'), ('designed', 'to', 'automatically'), ('to', 'automatically', 'extract'), ('automatically', 'extract', 'semantic'), ('extract', 'semantic', 'topics'), ('semantic', 'topics', 'from'), ('topics', 'from', 'documents'), ('from', 'documents', ','), ('documents', ',', 'as'), (',', 'as', 'efficiently'), ('as', 'efficiently', '('), ('efficiently', '(', 'computer-wise'), ('(', 'computer-wise', ')'), ('computer-wise', ')', 'and'), (')', 'and', 'painlessly'), ('and', 'painlessly', '('), ('painlessly', '(', 'developer-wise'), ('(', 'developer-wise', ')'), ('developer-wise', ')', 'as'), (')', 'as', 'possible'), ('as', 'possible', '.'), ('possible', '.', 'each'), ('.', 'each', 'word'), ('each', 'word', 'extracted'), ('word', 'extracted', 'is'), ('extracted', 'is', 'associated'), ('is', 'associated', 'with'), ('associated', 'with

6.  Compute frequency distribution: Calculate the frequency distribution of the trigrams in the text:

In [34]:
freq_dist = FreqDist(trigrams)

 7. Display the most common N-Grams: Print the most common N-grams and their frequencies:

In [35]:
print("Most common trigrams:", freq_dist.most_common(5))

Most common trigrams: [(('the', 'quick', 'brown'), 2), (('quick', 'brown', 'fox'), 2), (('brown', 'fox', 'jumps'), 1), (('fox', 'jumps', 'over'), 1), (('jumps', 'over', 'the'), 1)]


The number next to each tuple indicates how frequently that particular trigram appears in the text. Each tuple represents a trigram that was taken from the text. This result offers an overview of the most common contextual patterns found in the supplied text.

 ## Word embeddings
 A complex technique in NLP is word embeddings, which convert textual data into a numerical representation by mapping words with similar meanings to nearby points in a high-dimensional space. This method is an effective tool for many NLP applications, including text classification, sentiment analysis, and machine translation. It makes it easier to catch contextual subtleties, syntactic patterns, and semantic commonalities within the language.

The idea behind word embeddings is that words that appear in comparable settings are probably going to have similar meanings. The foundation of several embedding models, including Word2Vec, GloVe, and FastText, is this idea, which is frequently captured in the distributional hypothesis of linguistics.

 ### Word embeddings techniques
 Creating word embeddings usually entails the following crucial steps:

  * Corpus preparation: In order to examine the linguistic context of each word, a sizable corpus of text is needed.

  * Tokenization: Tokens, typically words, are used to represent the text.

  * Model selection: Selecting an embedding model (Word2Vec, GloVe, or another) that meets the requirements of the application.

  * Training: Using the text data, the model is taught to anticipate words based on their contexts, or vice versa, acquiring the embeddings in the process.

  * Dimensionality reduction: Compared to the initial vocabulary size, the word characteristics are projected into a vector space with substantially fewer dimensions.

  * Normalization and usage: These vectors can be used for downstream NLP tasks after being normalized post-training.

  Each of these stages helps to build a vector space model in which a dense vector of floating-point values represents each unique word in the corpus. Embeddings capture far greater information about word usage and meanings than more basic BoW models.


### Recipe 4: Word embeddings
This recipe will guide you through the implementation of word embeddings using the Word2Vec model from the Gensim library. The following steps will help you understand how to perform word embeddings in Python:

 1. Install required libraries: Ensure the Gensim library is installed, as it provides an efficient implementation of Word2Vec:

In [36]:
!pip install gensim
!pip install nltk

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 17.5 MB/s eta 0:00:00


2.  Import necessary modules:

In [37]:
from gensim.models import Word2Vec
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


3.  Prepare sample text:

In [38]:
text = "Gensim is a free Python library designed to automatically extract semantic topics from documents, as efficiently (computer-wise) and painlessly (developer-wise) as possible. Each word extracted is associated with a semantically similar word and related with the key word with a score."

4. Tokenize and preprocess:

In [39]:
tokens = word_tokenize(text.lower())

5. Create and train the Word2Vec model:

In [40]:
model = Word2Vec([tokens], vector_size=100, window=5, min_count=1, workers=4)

6.  Access word embeddings:

In [41]:
vector = model.wv['semantic']

7.  Find similar words:

In [42]:
similar_words = model.wv.most_similar('semantic', topn=5)
print("Vector for semantic", vector)
print("Similar Words to semantic", similar_words)

Vector for semantic [ 0.00211889  0.00574647 -0.00211601  0.00318062  0.00844075  0.00037899
  0.00631825 -0.00672272  0.00656579  0.00468595  0.00508208 -0.00993945
 -0.00043413  0.00320641 -0.00583989 -0.00670684  0.00637498 -0.0068211
 -0.0051821   0.00808776 -0.00701197  0.00853091  0.00065784  0.00440535
 -0.0030268  -0.00543168 -0.00894951 -0.00061628 -0.00511509 -0.00309121
  0.00813518 -0.00765193 -0.00630022 -0.00528711 -0.00660457 -0.00885602
 -0.00109269  0.00945071  0.00802604 -0.00526833 -0.00813888 -0.00228747
 -0.00926502 -0.00505394 -0.00593552  0.00301965 -0.00756452  0.00123869
  0.00229637  0.00531637 -0.00202105 -0.00977121  0.00523478 -0.00589901
  0.00487056  0.00197223  0.00883447  0.00151782 -0.00184498  0.00650449
 -0.0070556  -0.00841058  0.00380306 -0.00256828 -0.0041954  -0.00190935
 -0.00988587  0.00027782 -0.00106393 -0.00296801  0.00249493  0.0046959
  0.0063657  -0.00790668 -0.00496749 -0.00878171 -0.00894092 -0.00370515
 -0.00126287 -0.00822483 -0.00538

A closer look at the parameter settings

https://kavita-ganesan.com/gensim-word2vec-tutorial-starter-code/

 ## Sentence embeddings
 Word embeddings offer a sophisticated semantic representation of words, which is a significant advancement in NLP. Important contextual linkages and similarities can be captured by using models such as Word2Vec. Due to this, embeddings are now essential to contemporary NLP systems, allowing computers to analyze human language in a contextually rich and computationally efficient manner.

###  Sentence embeddings techniques
Sentences are converted into numerical vectors, each of which reflects semantic information that the sentence encodes. This process creates sentence embeddings. Several crucial steps are included in this transformation process:

* Text collection and preprocessing: A sizable corpus of text is collected and subjected to preprocessing, which includes standardizing case and punctuation and sometimes eliminating less informative textual elements like stopwords.

* Vectorization strategy: Sentences are vectorized using a suitable technique. This could entail more sophisticated techniques utilizing neural networks or just a straightforward word vector average.

* Model training: To determine the most effective way to represent words as vectors, a model is trained using the corpus. This may entail supervised learning from labeled text data or unsupervised learning from the original text.

* Dimensionality reduction: To reduce the dimensionality of the sentence vectors while maintaining their semantic features, methods like principal component analysis (PCA) are used.

* Normalization: By guaranteeing that each vector fits within a comparable scale, the vectors are normalized, which improves the efficiency of subsequent activities such as similarity measurement.

* Usage in downstream tasks: The extensive semantic information these embeddings provide makes them useful as inputs for a variety of NLP tasks.

These embeddings’ primary objective is to simplify sentences while maintaining their semantic meaning, enabling computers to comprehend and analyze vast amounts of material with ease.

###  Recipe 5: Sentence embeddings
The following recipe steps show how to use the Doc2Vec model, an extension of the Word2Vec methodology that handles longer text units like sentences or paragraphs, to create simple sentence embeddings using Python’s Gensim package:

1.  Install required libraries: Ensure that you have Gensim installed, along with NLTK for basic text processing:

In [43]:
!pip install gensim
!pip install nltk

2.  Import necessary modules:

In [44]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


3.  Prepare and tag the data: Prepare your corpus by tagging each document. This is essential for Doc2Vec to identify and learn from individual text units:

In [45]:
text_corpus = [
    "Deep learning achieves great success in various AI fields.",
   "Transformers is a deep neural network that is fundamental in field of generative AI",
   "The representation of words as vectors facilitates understanding."
 ]
tagged_data = [TaggedDocument(words=word_tokenize(_d.lower()), tags=[str(i)]) for i, _d in enumerate(text_corpus)]
tagged_data

[TaggedDocument(words=['deep', 'learning', 'achieves', 'great', 'success', 'in', 'various', 'ai', 'fields', '.'], tags=['0']),
 TaggedDocument(words=['transformers', 'is', 'a', 'deep', 'neural', 'network', 'that', 'is', 'fundamental', 'in', 'field', 'of', 'generative', 'ai'], tags=['1']),
 TaggedDocument(words=['the', 'representation', 'of', 'words', 'as', 'vectors', 'facilitates', 'understanding', '.'], tags=['2'])]

 4. Create the model: Instantiate and train a Doc2Vec model:

In [46]:
model = Doc2Vec(vector_size=100, window=2, min_count=1, workers=4, epochs=40)
model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)

5.  Generate sentence embeddings: Retrieve vector embeddings for each sentence:

In [47]:
sentence_vectors = [model.dv[str(i)] for i in range(len(text_corpus))]
sentence_vectors

[array([-5.8905939e-03, -6.5310788e-03, -1.0197518e-02,  9.1153858e-03,
         3.6636097e-03,  1.5976530e-05, -9.9860746e-03, -4.8974487e-03,
        -9.9671315e-03,  2.1136487e-03,  2.7258364e-03,  4.7481242e-03,
        -4.7327681e-03, -3.4769641e-03, -2.7894778e-03, -9.1638546e-03,
         2.1140454e-03,  9.5962780e-03, -9.8759076e-03, -3.6865226e-03,
        -3.7555227e-03,  2.7417552e-03, -5.8743665e-03,  3.2447244e-03,
         5.3710053e-03, -8.2173580e-03, -9.2407595e-03, -1.0273106e-02,
         5.1474012e-03, -9.6719265e-03,  6.3431328e-03,  6.7987130e-03,
        -6.5899240e-03, -5.0020088e-03, -1.6101694e-03,  1.9060184e-03,
        -1.4732652e-03, -8.9521641e-03, -4.2036441e-03,  1.3896329e-03,
        -1.3650382e-03, -7.3935450e-03,  4.6294006e-03, -9.1171376e-03,
         2.6103102e-03, -4.9956790e-03,  5.0612772e-04, -1.8047850e-03,
         5.6209019e-03, -8.8008968e-03, -2.5908989e-03, -1.2937242e-04,
        -6.9886115e-03, -7.2710402e-03, -2.3293553e-03,  9.70883

6.  Use embeddings for similarity comparison: Demonstrate the use of embedding by finding similarity between sentences:

In [48]:
similarity = model.dv.n_similarity(['0'], ['1'])

In [49]:
print("Similarity between first two sentences:", similarity)

Similarity between first two sentences: 0.23607786


A sentence from the corpus is embedded into each vector in the output, which is a dense vector of floating point values. Based on their embeddings, the similarity score shows how semantically similar the first two sentences are to one another.

## BERT
The emergence of models such BERT marks a paradigm shift in the field of NLP as it pertains to the understanding of human language by machines. Google created BERT, a pre-trained model that uses conditioning on both left and right context in all levels to pre-train deep bidirectional representations. Therefore, without requiring significant task-specific architecture modifications, the pre-trained BERT model may be refined with just one more output layer to produce state-of-the-art models for a variety of tasks, including question answering, sentiment analysis, and language inference.

 ### BERT techniques
 BERT’s transformer architecture, which powers its profound comprehension of linguistic context and nuance, is the key to its efficacy. Several essential steps are involved in using BERT:

* Pre-training: BERT is first pre-trained on a sizable corpus of text, gaining a broad grasp of context and linguistic structure.

* Tailoring: Additional task-specific layers can be added to BERT to fine-tune it for particular activities. This is merely tweaking the model to fit the specifics of the intended purpose.

* Tokenization: The WordPiece tokenization technique must be used to tokenize text in a particular way for BERT to function. This deconstructs words into smaller, more digestible chunks so that embeddings can be learned more successfully.

* Embedding extraction: To capture deep contextual links, BERT transforms these tokens into embeddings, which are subsequently processed through its layers of neural networks.

* Output layer: Various output layers, such as classification layers for sentiment analysis, can be built on top of BERT to generate predictions, depending on the task at hand.

* Inference: Using fresh input text, the refined model is subsequently utilized to infer or forecast results.

BERT’s power is in its deep contextual insights, which allow it to adapt to a wide range of NLP jobs with little change.

 ### Recipe 6: BERT
 This recipe walks you through the use of the Hugging Face transformers library, a well-liked toolkit that offers a simple API to interact with BERT and other transformer models, to create BERT for a classification assignment. The following steps will help you understand how to use BERT in Python:

1.  Install required libraries: Ensure that you have the transformers and torch libraries installed:



In [50]:
!pip install transformers
!pip install torch

2. Import necessary modules:

In [51]:
from transformers import BertTokenizer, BertForSequenceClassification
from torch.nn.functional import softmax
import torch

3.  Load pre-trained BERT model and tokenizer:

In [52]:
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.weight                | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

4.  Prepare input text:

In [53]:
text = "BERT revolutionizes natural language processing."
encoded_input = tokenizer(text, return_tensors='pt')
encoded_input

{'input_ids': tensor([[  101, 14324,  4329, 10057,  3019,  2653,  6364,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

5.  Model prediction:

In [54]:
import torch.nn.functional as F
output = model(**encoded_input)
predictions = F.softmax(output.logits, dim=-1)

6.  Interpret the output:

In [55]:
predicted_class = torch.argmax(predictions).item()
print("Predicted class:", predicted_class)

Predicted class: 0


This predicted class shows the model’s choice depending on the fine-tuning it has received; for example, it may be able to discriminate between different text kinds based on the training it has received (e.g., sentiment, positive or negative).

##  One-hot encoding
In machine learning processes, one-hot encoding is a key technique that transforms categorical input into a numerical representation. It is extensively utilized for processing both textual and categorical data. One-hot encoding converts words into vectors for use in NLP. Each word is represented by a vector with one hot (1) element and all other elements being cold (0). This method offers a concise, although not semantically rich, representation of text data, making it especially helpful for models that need numerical input.

 ### One-hot encoding techniques
 One-hot encoding requires the following crucial steps:

* Vocabulary creation: Every term (vocabulary) that appears in the dataset is listed individually.

* Vector representation: A vector represents each word in the lexicon. This vector’s length corresponds to the vocabulary’s size.

* Encoding: Every word in its vector has its associated index set to 1, and all other locations are set to 0.

* Context ignorance: It is crucial to remember that one-hot encoding does not save word relationships or other contextual information. Every word has its own unique encoding.

* Sparsity: As the vocabulary expands, the sparse (mainly zeros) vectors produced by one-hot encoding may become computationally demanding.

Although this approach is straightforward, it serves as a foundation for more intricate representations and is employed in several neural network and algorithm preprocessing stages that demand a fixed-length input.

###  Recipe 8: One-hot encoding
This recipe will demonstrate how to implement one-hot encoding from scratch and with the use of high-level libraries in Python:

1.  Install required libraries:

In [56]:
!pip install numpy
!pip install scikit-learn

2.  Import necessary modules:

In [57]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

3. Define sample text:

In [58]:
words = ['apple', 'orange', 'banana', 'apple', 'orange']

4. Create unique word index:

In [59]:
word_dict = {word: idx for idx, word in enumerate(sorted(set(words)))}

5. Encode using custom function:

In [60]:
def one_hot_encode(word):
  vector = np.zeros(len(word_dict))
  vector[word_dict[word]] = 1
  return vector

encoded_words = np.array([one_hot_encode(word) for word in words])

6. Use scikit-learn for one-hot encoding:

In [61]:
encoder = OneHotEncoder(sparse_output=False)
encoded_words_sklearn=encoder.fit_transform(np.array(words).reshape(-1, 1))

7. Display the encoded vectors:


In [62]:
print("Custom One-Hot Encoding:\n", encoded_words)
print("Scikit-Learn One-Hot Encoding:\n", encoded_words_sklearn)

Custom One-Hot Encoding:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Scikit-Learn One-Hot Encoding:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


Words in the input are represented by rows in the matrix, and the presence of a word is indicated by a 1 in each row according to its indexed position as defined by the vocabulary’s alphabetical order.

## More topics in the chaper:
* Semantic clustering
* Cosine similarity
* Relationship extraction

## Conclusion

Conclusion

This chapter has explored the landscape of semantic representation techniques in NLP, from the simplest to the most advanced methods. Each technique adds unique value, providing essential tools for transforming unstructured text into structured data, forming the foundation for NLP applications across diverse domains.

Starting with the BoW model, we saw how it transforms text into a structured format, serving as a steppingstone for more sophisticated techniques.

TF-IDF and N-Gram Modeling address BoW’s limitations by weighting terms and capturing contextual information.

Word and sentence embeddings revolutionized semantic representation, enabling machines to recognize subtle semantic differences and similarities. Embeddings are crucial for tasks like sentiment analysis, semantic search, and dialogue systems.

Pre-trained language models, such as BERT, have ushered in a new era in NLP by understanding language in a bidirectional context, dramatically improving the effectiveness and efficiency of numerous applications.

The semantic representation techniques covered are practical tools with a wide range of applications, enabling machines to perform tasks that require human-like language understanding.

Looking ahead, the upcoming chapter on entity recognition will delve into POS tagging, entity classification, and the processes involved in extracting and disambiguating entities. It will explore developing custom entity recognizers, integrating named entity recognition (NER) with other NLP tasks, and evaluating model performance in real-world scenarios.

The next chapter will equip readers with the tools and knowledge to implement these advanced methodologies, accelerating the transformation of raw data into actionable insights and contributing to the ever-evolving field of NLP.
